### ISSUE TITLE
Creació del mòdul

### ISSUE THREAD

**Issue by xxjcaxx** [xxjcaxx/sge2425#1]
Fer el scaffold del mòdul i fer que s'instal·le i funcione mínimament en el menú.

- [ ] Fer scaffold
- [ ] Crear el primer model `player`
- [ ] Crear els primers permisos de `player`
- [ ] Modificar el `manifest` per a que funcionen els permisos i la vista mínima.
- [ ] Crear els 3 nivells de menú per al `player`
- [ ] Instal·lar i confirmar que funciona.

**Comment by ToniRumen** [comment]
Pruebasss
