### ISSUE TITLE
dragon

### ISSUE THREAD

**Issue by xxjcaxx** [xxjcaxx/sge2425#12]
Fa que "entrenen" els personatges

level

player

**Comment by AlejandroBlascoChafer** [comment]
ñ

**Comment by ericgarcia101** [comment]
hola

**Comment by Armantk03** [comment]
pitufina

**Comment by EnriqueNavarroMartinez** [comment]
hola

**Comment by manelNunez** [comment]
Cuidado odoo

**Comment by VIZ3NT04** [comment]
tamaremelaenseña

**Comment by davpalmol** [comment]
viva españa

**Comment by pautpdam** [comment]
o/

**Comment by danfraher** [comment]
si.

**Comment by JPTER78** [comment]
SanchoPanza

**Comment by PabloEdD** [comment]
OSError: [Errno 98] Address already in use

**Comment by pablo7843** [comment]
enrique pastor concejal de juventud y tiempo libre

**Comment by JPTER78** [comment]
![giphy](https://github.com/user-attachments/assets/7e968f5f-0834-420d-b9ea-f6ba3393cd4b)

**Comment by ToniRumen** [comment]
خيمو تقاعد

**Comment by pautpdam** [comment]
> خيمو تقاعد

![image](https://github.com/user-attachments/assets/cbe82f1c-c2e7-4db2-91e9-b295429c2c6a)
XD?
